/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rReXj6Nm0nC
 */
"use client"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import PieChart from "./pie-chart"

import data from '../../data/checks.json';

export function CheckTable() {
  return (
    <Table className="w-full">
      <TableHeader>
        <TableRow>
          <TableHead className="w-[200px] bg-custom-blue">Test Name</TableHead>
          <TableHead className="w-[100px] bg-custom-red">Passed %</TableHead>
          <TableHead className="w-[200px] bg-custom-yellow">Diagram</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {data.map((test, index) => (
          <TableRow key={index}>
            <TableCell className="font-medium">{test.name}</TableCell>
            <TableCell>{test.passedRatio}</TableCell>
            <TableCell>
              <PieChart className="w-[100px] aspect-square" passed={test.passed} failed={test.failed} />
            </TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  )
}
